import { test as base, Page } from '@playwright/test';
import fs from 'fs';
import path from 'path';

/**
 * Custom test fixtures for authentication
 *
 * These fixtures provide additional authentication utilities
 * for tests that need special authentication scenarios.
 * Uses Supabase email/password authentication via the E2E helper page.
 */

type AuthFixtures = {
  authenticatedPage: Page;
  loggedOutPage: Page;
  adminPage: Page;
};

export const test = base.extend<AuthFixtures>({
  /**
   * Page fixture with standard user authentication
   * Uses the storageState from the setup
   */
  authenticatedPage: async ({ browser }, use) => {
    const storageStatePath = path.join(__dirname, '..', 'storageState.auth.json');

    const context = await browser.newContext({
      storageState: storageStatePath
    });

    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page fixture with no authentication
   * Useful for testing login flows and public pages
   */
  loggedOutPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      // No storageState - starts fresh
    });

    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  /**
   * Page fixture with admin user authentication
   * Signs in via email/password using the Supabase E2E helper page
   */
  adminPage: async ({ browser }, use) => {
    const context = await browser.newContext();
    const page = await context.newPage();

    try {
      // Authenticate as admin using email/password via Supabase
      await AuthUtils.signInWithEmail(page, TEST_USERS.ADMIN.email, TEST_USERS.ADMIN.password);

      await use(page);
    } finally {
      await context.close();
    }
  },
});

export { expect } from '@playwright/test';

/**
 * Utility functions for Supabase authentication in tests
 */
export class AuthUtils {
  /**
   * Sign in a user with email/password via the E2E helper
   */
  static async signInWithEmail(page: Page, email: string, password: string) {
    await page.goto(`/__e2e-login.html?mode=email&email=${encodeURIComponent(email)}&password=${encodeURIComponent(password)}`);

    await page.waitForFunction(
      () => {
        const status = document.body.getAttribute('data-auth-status');
        return status === 'success' || status === 'error' || document.body.textContent === 'OK';
      },
      { timeout: 15000 }
    );

    const authStatus = await page.getAttribute('body', 'data-auth-status');
    if (authStatus === 'error') {
      const errorMessage = await page.getAttribute('body', 'data-auth-message');
      throw new Error(`Authentication failed: ${errorMessage}`);
    }

    // Navigate back to main app
    await page.goto('/');
  }

  /**
   * Sign out the current user
   */
  static async signOut(page: Page) {
    await page.goto('/__e2e-login.html?mode=logout');

    await page.waitForFunction(
      () => document.body.textContent === 'OK',
      { timeout: 10000 }
    );
  }

  /**
   * Check if a user is currently signed in
   */
  static async isSignedIn(page: Page): Promise<boolean> {
    await page.goto('/__e2e-login.html?mode=check');

    await page.waitForFunction(
      () => {
        const text = document.body.textContent;
        return text?.startsWith('SIGNED_IN:') || text === 'NOT_SIGNED_IN';
      },
      { timeout: 10000 }
    );

    const bodyText = await page.textContent('body');
    return bodyText?.startsWith('SIGNED_IN:') || false;
  }

  /**
   * Get current user ID if signed in
   */
  static async getCurrentUserId(page: Page): Promise<string | null> {
    await page.goto('/__e2e-login.html?mode=check');

    await page.waitForFunction(
      () => {
        const text = document.body.textContent;
        return text?.startsWith('SIGNED_IN:') || text === 'NOT_SIGNED_IN';
      },
      { timeout: 10000 }
    );

    const bodyText = await page.textContent('body');
    if (bodyText?.startsWith('SIGNED_IN:')) {
      return bodyText.split(':')[1];
    }
    return null;
  }
}

/**
 * Load user UUIDs from the e2e-users.json file generated by the seed script.
 * Returns an empty object if the file does not exist yet.
 */
function loadE2EUserIds(): Record<string, string> {
  try {
    const filePath = path.join(__dirname, 'e2e-users.json');
    const raw = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(raw) as Record<string, string>;
  } catch {
    return {};
  }
}

const _userIds = loadE2EUserIds();

/**
 * Test user credentials for convenience.
 * UIDs are loaded dynamically from tests/fixtures/e2e-users.json
 * which is generated by the seed script.
 */
export const TEST_USERS = {
  REGULAR: {
    email: 'e2e@example.com',
    password: 'test1234',
    uid: _userIds['e2e@example.com'] ?? ''
  },
  SECOND: {
    email: 'e2e2@example.com',
    password: 'test1234',
    uid: _userIds['e2e2@example.com'] ?? ''
  },
  ADMIN: {
    email: 'admin@example.com',
    password: 'admin1234',
    uid: _userIds['admin@example.com'] ?? ''
  }
};
