-- ================================================
-- Schema Normalization Migration
-- Migration: 20260106000001_normalize_schema
-- ================================================
-- NOTE: This migration is now a no-op.
--
-- The following normalizations were consolidated into the initial schema
-- (20260106000000_initial_schema.sql) to avoid unnecessary schema churn:
--
-- 1. waiting_users_ids array → board_waiting_users join table
--    (Initial schema creates board_waiting_users directly, no array column)
--
-- 2. known_buddy_nickname/known_buddy_profile_photo_url removed
--    (Initial schema only has known_buddy_uid as FK)
--
-- Historical Identity fields (user_name, user_profile_image) are
-- intentionally kept on comments, replies, likes, and reactions for:
-- 1. Performance: Avoids JOINs when loading PostDetailPage
-- 2. Authenticity: Preserves identity at the moment of interaction

-- No operations needed - schema is already normalized in initial migration.
