// src/firebase/constants.ts

// Time constants
export const TIME_CONSTANTS = {
  SECOND_IN_MS: 1000,
  MINUTE_IN_SECONDS: 60,
} as const;

// Remote Config fetch intervals
export const REMOTE_CONFIG_INTERVALS = {
  DEVELOPMENT_MINUTES: 1,
  PRODUCTION_MINUTES: 5,
} as const;

export const REMOTE_CONFIG_FETCH_INTERVALS = {
  DEVELOPMENT:
    REMOTE_CONFIG_INTERVALS.DEVELOPMENT_MINUTES *
    TIME_CONSTANTS.MINUTE_IN_SECONDS *
    TIME_CONSTANTS.SECOND_IN_MS,
  PRODUCTION:
    REMOTE_CONFIG_INTERVALS.PRODUCTION_MINUTES *
    TIME_CONSTANTS.MINUTE_IN_SECONDS *
    TIME_CONSTANTS.SECOND_IN_MS,
} as const;

// Default emulator configuration
export const DEFAULT_EMULATOR_CONFIG = {
  HOST: 'localhost',
  PORTS: {
    FIRESTORE: '8080',
    STORAGE: '9199',
    FUNCTIONS: '5001',
  },
  RADIX: 10, // For parseInt base
} as const;

// Firebase configuration keys
export const FIREBASE_CONFIG_KEYS = {
  API_KEY: 'VITE_FIREBASE_API_KEY',
  AUTH_DOMAIN: 'VITE_FIREBASE_AUTH_DOMAIN',
  PROJECT_ID: 'VITE_FIREBASE_PROJECT_ID',
  STORAGE_BUCKET: 'VITE_FIREBASE_STORAGE_BUCKET',
  MESSAGING_SENDER_ID: 'VITE_FIREBASE_MESSAGING_SENDER_ID',
  APP_ID: 'VITE_FIREBASE_APP_ID',
  MEASUREMENT_ID: 'VITE_FIREBASE_MEASUREMENT_ID',
} as const;

// Environment variable keys
export const ENV_KEYS = {
  USE_EMULATORS: 'VITE_USE_EMULATORS',
  EMULATOR_FIRESTORE_HOST: 'VITE_EMULATOR_FIRESTORE_HOST',
  EMULATOR_FIRESTORE_PORT: 'VITE_EMULATOR_FIRESTORE_PORT',
  EMULATOR_STORAGE_HOST: 'VITE_EMULATOR_STORAGE_HOST',
  EMULATOR_STORAGE_PORT: 'VITE_EMULATOR_STORAGE_PORT',
  EMULATOR_FUNCTIONS_HOST: 'VITE_EMULATOR_FUNCTIONS_HOST',
  EMULATOR_FUNCTIONS_PORT: 'VITE_EMULATOR_FUNCTIONS_PORT',
} as const;

// Error messages
export const ERROR_MESSAGES = {
  EMULATOR_START_COMMAND: 'Make sure Firebase emulators are running: firebase emulators:start',
} as const;
