name: Coverage report by Vitest

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest Coverage
        run: npm run test:run -- --coverage

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # json-summary-path: coverage/coverage-summary.json
          # json-final-path: coverage/coverage-final.json
          # file-coverage-mode: changes
          # comment-on: pr,commit
